# Each hash must include :name, :description, :category, :complexity_key
DEFAULT_VFX_ASSUMPTIONS = [
  { name: "Green screen keying",           description: "Key out green screen background",            category: "Compositing / Plate Work", complexity_key: "comp_basic" },
  { name: "Blue screen keying",            description: "Key out blue screen background",             category: "Compositing / Plate Work", complexity_key: "comp_basic" },
  { name: "Luma keying",                   description: "Key based on luminance",                     category: "Compositing / Plate Work", complexity_key: "comp_basic" },
  { name: "Rig removal",                   description: "Remove rigs and supports",                   category: "Compositing / Plate Work", complexity_key: "prep_simple" },
  { name: "Wire/marker removal",           description: "Remove wires and tracking markers",          category: "Compositing / Plate Work", complexity_key: "prep_simple" },
  { name: "Plate stabilization",           description: "Stabilize shaky footage",                   category: "Compositing / Plate Work", complexity_key: "prep_simple" },
  { name: "Reprojection / matchmove patching", description: "Patch plates via projection & matchmove", category: "Compositing / Plate Work", complexity_key: "prep_simple" },
  { name: "Smoke simulation",              description: "Simulate smoke using fluid solver",         category: "FX / Simulations",            complexity_key: "fx_high" },
  { name: "Fire simulation",               description: "Simulate fire and embers",                   category: "FX / Simulations",            complexity_key: "fx_high" },
  { name: "Dust / debris simulation",      description: "Simulate dust and debris",                   category: "FX / Simulations",            complexity_key: "fx_medium" },
  { name: "Fluid simulation",              description: "Simulate liquids with fluid solver",         category: "FX / Simulations",            complexity_key: "fx_high" },
  { name: "Foam/splashes",                 description: "Add foam and splashes",                      category: "FX / Simulations",            complexity_key: "fx_medium" },
  { name: "Rain / snow / hail",            description: "Particle rain or snow sim",                  category: "FX / Simulations",            complexity_key: "fx_medium" },
  { name: "Wind interaction",              description: "Simulate wind on cloth, hair, foliage",      category: "FX / Simulations",            complexity_key: "sim_vhigh" },
  { name: "Destruction simulation",        description: "Simulate structural destruction",            category: "FX / Simulations",            complexity_key: "fx_high" },
  { name: "Bullet impact / explosion sim", description: "Bullet hit and explosion sim",             category: "FX / Simulations",            complexity_key: "fx_high" },
  { name: "Particle trails / sparks / embers", description: "Particles trailing from fracturing or burning", category: "FX / Simulations", complexity_key: "fx_medium" },
  { name: "Rotoscoping",                   description: "Manual roto of characters or props",         category: "Roto / Prep",                 complexity_key: "roto_medium" },
  { name: "Garbage matte creation",        description: "Create rough mattes to isolate elements",    category: "Roto / Prep",                 complexity_key: "roto_medium" },
  { name: "Edge softening / choking",      description: "Refine matte edges for clean composites",    category: "Roto / Prep",                 complexity_key: "roto_medium" },
  { name: "3D camera tracking",            description: "Matchmove a 3D camera solve",                category: "Tracking / Matchmoving",      complexity_key: "fx_medium" },
  { name: "Object tracking",               description: "Track moving objects (rigid/deformable)",   category: "Tracking / Matchmoving",      complexity_key: "fx_medium" },
  { name: "CG set extension",              description: "Extend set with CG geometry & textures",     category: "3D / CG Assumptions",         complexity_key: "cg_prop_basic" },
  { name: "Digital double creation",       description: "Build and skin a digital stunt double",      category: "3D / CG Assumptions",         complexity_key: "creature_high" },
  { name: "AI-assisted rotoscoping",       description: "Use ML to speed up roto masks",              category: "AI / ML-Assisted Techniques", complexity_key: "pipeline_medium" },
  { name: "Depth map generation",          description: "Generate depth maps for stereo conversion",  category: "Pipeline / Technical Passes",  complexity_key: "pipeline_medium" },
  { name: "Burn-in / timecode overlay",    description: "Add burn-in text or timecode",               category: "Delivery / Review Prep",       complexity_key: "delivery_low" },
  { name: "Cryptomatte pass generation",   description: "Generate crypto mattes for object mattes",   category: "Pipeline / Technical Passes",  complexity_key: "pipeline_medium" },
  { name: "Stereo conversion assumptions", description: "Convert 2D to 3D with depth grading",       category: "Stereo / 3D Conversion",      complexity_key: "stereo_medium" },
  { name: "Letterboxing / cropping",       description: "Apply letterbox or crop framing",            category: "Delivery / Review Prep",       complexity_key: "delivery_low" },
  { name: "OCIO color space config",       description: "Setup color pipeline with OCIO",             category: "Pipeline / Technical Passes",  complexity_key: "pipeline_medium" },
  { name: "Plate relink / shot update",    description: "Swap out plates or update shot assets",      category: "General / Management Assumptions", complexity_key: "delivery_low" }
].freeze
